#cloud-config

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
  units:
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=<%= ENV['SSH_PORT'] || '22' %>
        Accept=yes

    - name: docker.service
      runtime: yes
      drop-ins:
        - name: 50-log-level.conf
          content: |
            [Service]
            Environment='DOCKER_OPTS=--log-level=warn'
